version: '3.8'

services:
  mysql:
    container_name: ms_mysql_book_store
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - microservices-net

  config-server-service:
    build:
      context: ../../bookStore-backend/services/config-server
    networks:
      - microservices-net
    depends_on:
      - mysql

  discovery-service:
    build:
      context: ../../bookStore-backend/services/discovery
    networks:
      - microservices-net
    depends_on:
      - mysql

  gateway-service:
    build:
      context: ../../bookStore-backend/services/gateway
    networks:
      - microservices-net
    depends_on:
      - discovery-service
      - config-server-service

  books-service:
    build:
      context: ../../bookStore-backend/services/book
    networks:
      - microservices-net
    depends_on:
      - mysql
      - discovery-service
      - config-server-service

  carts-service:
    build:
      context: ../../bookStore-backend/services/cart
    networks:
      - microservices-net
    depends_on:
      - mysql
      - discovery-service
      - config-server-service

  orders-service:
    build:
      context: ../../bookStore-backend/services/order
    networks:
      - microservices-net
    depends_on:
      - mysql
      - discovery-service
      - config-server-service

  shippings-service:
    build:
      context: ../../bookStore-backend/services/shipping
    networks:
      - microservices-net
    depends_on:
      - mysql
      - discovery-service
      - config-server-service

  users-service:
    build:
      context: ../../bookStore-backend/services/user
    networks:
      - microservices-net
    depends_on:
      - mysql
      - discovery-service
      - config-server-service

networks:
  microservices-net:
    driver: bridge
