CREATE DATABASE IF NOT EXISTS books_db;
CREATE DATABASE IF NOT EXISTS carts_db;
CREATE DATABASE IF NOT EXISTS orders_db;
CREATE DATABASE IF NOT EXISTS shippings_db;
CREATE DATABASE IF NOT EXISTS users_db;