eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false

management:
  endpoints:
    web:
      exposure:
        include: health