spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_store_db
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

axon:
  axonserver:
    enabled: false

server:
  port: 8010

application:
  config:
    book-url: http://localhost:8222/api/v1/books
    cart-url: http://localhost:8222/api/v1/carts
    cart-item-url: http://localhost:8222/api/v1/cart-items
    order-url: http://localhost:8222/api/v1/orders
    shipping-order-url: http://localhost:8222/api/v1/shippings