spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
      routes:
        - id: book-service
          uri: lb:http://BOOK-SERVICE
          predicates:
            - Path=/api/v1/books/**
        - id: category-service
          uri: lb:http://BOOK-SERVICE
          predicates:
            - Path=/api/v1/categories/**
        - id: cart-service
          uri: lb:http://CART-SERVICE
          predicates:
            - Path=/api/v1/carts/**
        - id: cart-items-service
          uri: lb:http://CART-SERVICE
          predicates:
            - Path=/api/v1/cart-items/**
        - id: order-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
        - id: order-details-service
          uri: lb:http://ORDER-SERVICE
          predicates:
            - Path=/api/v1/order-details/**
        - id: shipping-service
          uri: lb:http://SHIPPING-SERVICE
          predicates:
            - Path=/api/v1/shippings/**
        - id: user-service
          uri: lb:http://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: composition-service
          uri: lb:http://COMPOSITION-SERVICE
          predicates:
            - Path=/api/v1/composition/**
        - id: order-query-service
          uri: lb:http://ORDER-QUERY-SERVICE
          predicates:
            - Path=/api/v1/orders-query/**

server:
  port: 8222